include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - tools/out/**
    - packages/flutter_scene_viewer_basisu/**
    - packages/flutter_scene_viewer_draco/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    unawaited_futures: true
